### ISSUE TITLE
Cannot find the qt platform plugin "xcb"

### ISSUE THREAD

**Issue by LrMissing** [opendesktop/opendesktop-app#45]
I just wanted to run opendesktop-app,but the errors occurs which the following list
```
➜  ~ uname -a
Linux archlinux 4.16.6-1-ARCH #1 SMP PREEMPT Mon Apr 30 12:30:03 UTC 2018 x86_64 GNU/Linux
```
```
➜  bin ./opendesktop-app-3.1.1-1-x86_64.AppImage 
{ Error: Command failed: /tmp/.mount_opendemw3KEs/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd: '/tmp/.mount_opendemw3KEs/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0' }
```
How can I fix this problem or which depends should I install?

**Comment by star-buck** [comment]
Can we package those dependencies in the appimage?

**Comment by LrMissing** [comment]
@akiraohgaki 
Thanks for your reply.
But,it seems do nothing help to fix this issue.When I was trying to install the depends that you had suggested, I found the depends had already installed.
By the way, my desktop environment is kde plasma 5, and system os is archlinux with latest updates.
The following is the message print list:
```
➜  ~ sudo pacman -S qt5-base libcanberra libgnome-keyring
warning: qt5-base-5.10.1-8 is up to date -- reinstalling
warning: libcanberra-0.30+2+gc0620e4-1 is up to date -- reinstalling
warning: libgnome-keyring-3.12.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (3) libcanberra-0.30+2+gc0620e4-1  libgnome-keyring-3.12.0-2  qt5-base-5.10.1-8

Total Download Size:    0.20 MiB
Total Installed Size:  59.27 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 libcanberra-0.30+2+gc0620e4-1-x86_64                    78.7 KiB   606K/s 00:00 [##############################################] 100%
 libgnome-keyring-3.12.0-2-x86_64                       126.5 KiB   603K/s 00:00 [##############################################] 100%
(3/3) checking keys in keyring                                                   [##############################################] 100%
(3/3) checking package integrity                                                 [##############################################] 100%
(3/3) loading package files                                                      [##############################################] 100%
(3/3) checking for file conflicts                                                [##############################################] 100%
(3/3) checking available disk space                                              [##############################################] 100%
:: Processing package changes...
(1/3) reinstalling qt5-base                                                      [##############################################] 100%
(2/3) reinstalling libcanberra                                                   [##############################################] 100%
(3/3) reinstalling libgnome-keyring                                              [##############################################] 100%
:: Running post-transaction hooks...
(1/2) Reloading system manager configuration...
(2/2) Arming ConditionNeedsUpdate...
➜  ~ ls
Desktop  Documents  Downloads  Github  history  need2cleandisk  Pictures
➜  ~ /opt/OpendesktopApp.AppImage 
{ Error: Command failed: /tmp/.mount_OpendeRx6bCE/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd: '/tmp/.mount_OpendeRx6bCE/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0' }
```

**Comment by akiraohgaki** [comment]
Sorry, this was libfreetype's compatibility problem.
And we making the fix version of opendesktop-app now.

**Comment by akiraohgaki** [comment]
Close this ticket.
Please see: https://github.com/opendesktop/opendesktop-app/issues/46
