### ISSUE TITLE
OpenDesktop App starts blank

### ISSUE THREAD

**Issue by claudiusraphaelpaeth** [opendesktop/opendesktop-app#46]
OpenDesktop App V.3.1.1.1 x86_64 starts with a blank window on fresh install of Ubuntu 18.04 LTS Bionic Beaver;

Following is output from terminal :

```
./Downloads/opendesktop-app-3.1.1-1-x86_64.AppImage
Gtk-Message: 07:48:57.263: Failed to load module "canberra-gtk-module"
{ Error: Command failed: /tmp/.mount_opendexEKb52/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.

    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd: '/tmp/.mount_opendexEKb52/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0' }


```

; nothing added on close of App-Window .

**Comment by star-buck** [comment]
@akiraohgaki : can you quickly fix this with an update?

**Comment by star-buck** [comment]
seems same as #45 ?

**Comment by akiraohgaki** [comment]
@claudiusraphaelpaeth 
Try to install these packages:
* libqt5gui5
* libcanberra-gtk-module
* libgnome-keyring0

**Comment by star-buck** [comment]
How about including those in the appimage?

**Comment by claudiusraphaelpaeth** [comment]
@akiraohgaki ; I added
- libqt5gui5
- libcanberra-gtk-module
- libgnome-keyring0
as mentioned; makes no difference.

Also tried solely as also in combination with the afore mentioned modules, the qt5dxcb-plugin as an alternative, which is the theme-integration of Qt 5 for the ' deepin DE '; Because it depends on Qt 5 libraries for X11 and Wayland and integrates what is left out on standard-bionic-install.
  But again, makes no difference.

Also added libcanberra-dev libcanberra-gtk-dev libcanberra-gtk3-dev just to check, but no difference anyhow.

Also, checked install of whole Qt5 Stack, just to finish the merry-go-round from the dependency-perspective. No difference, so i assume, there is just some wrong inside, without had having a look, yet.

I am testing Ubuntu 18.04 LTS Bionic Beaver in a bunch of configurations on different hardware in the upcoming weeks, so feel free, to add your ideas, i am sure i can integrate testing  the appimage, once or twice every now and then in between.

That's it for now. 

P.s.: Did you check KDE Neon? I would assume there's also a similar problem, due to the modified versions of Qt5 used in there?

**Comment by akiraohgaki** [comment]
Sorry, this was libfreetype's compatibility problem.
And we making the fix version of opendesktop-app now.

**Comment by LrMissing** [comment]
@akiraohgaki 
Thanks for your work~

**Comment by akiraohgaki** [comment]
@claudiusraphaelpaeth @LrMissing 
Please try opendesktop-app version 3.1.2, this version should be work without additional package installation.

**Comment by LrMissing** [comment]
Does anything I should do? 
I'm sorry to say that it seems the opendesktop-app version 3.1.2 doesn't fix the issue~~
```
➜  bin ls
opendesktop-app-3.1.2-1-x86_64.AppImage
➜  bin ./opendesktop-app-3.1.2-1-x86_64.AppImage 
{ Error: Command failed: /tmp/.mount_opendeBhvnrY/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.

    at ChildProcess.exithandler (child_process.js:287:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd: '/tmp/.mount_opendeBhvnrY/usr/lib/opendesktop-app-linux-x64/resources/app/bin/ocs-manager -p 0' }
```

**Comment by claudiusraphaelpaeth** [comment]
Confirmed;
: Version 3.1.2 works as intended on fresh install of Ubuntu 18.04 LTS Bionic Beaver Desktop x64

**Comment by akiraohgaki** [comment]
@LrMissing 
Please try opendesktop-app version 3.1.3.
This version works on Manjaro Linux, so possible to works on Arch Linux.

**Comment by LrMissing** [comment]
@akiraohgaki 
Oh,yes. It works.
Thank you so much.
